<?php

namespace Database\Seeders;

use App\Models\Brand;
use App\Models\VehicleModel;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class VehicleModelsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Получаем оригинальные бренды
        $brands = Brand::where('is_original', true)->get();

        // Массив популярных моделей автомобилей по РФ (топ-200)
        $popularModels = [
            ['brand' => 'Toyota', 'name' => 'Corolla', 'generation' => 'XII', 'start_year' => 2019, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Toyota', 'name' => 'Camry', 'generation' => 'VIII', 'start_year' => 2018, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Toyota', 'name' => 'RAV4', 'generation' => 'V', 'start_year' => 2018, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Toyota', 'name' => 'Land Cruiser', 'generation' => 'CC', 'start_year' => 2007, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Toyota', 'name' => 'Prius', 'generation' => 'IV', 'start_year' => 2015, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Toyota', 'name' => 'Hilux', 'generation' => 'VIII', 'start_year' => 2015, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Toyota', 'name' => 'Highlander', 'generation' => 'IV', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Toyota', 'name' => 'Fortuner', 'generation' => 'II', 'start_year' => 2015, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Toyota', 'name' => 'C-HR', 'generation' => 'I', 'start_year' => 2016, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Toyota', 'name' => 'Avensis', 'generation' => 'III', 'start_year' => 2012, 'end_year' => 2018, 'is_facelift' => true, 'facelift_year' => 2015],
            ['brand' => 'Toyota', 'name' => 'Yaris', 'generation' => 'IV', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Toyota', 'name' => 'Land Cruiser Prado', 'generation' => 'CL', 'start_year' => 2009, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2017],
            ['brand' => 'Toyota', 'name' => 'Sienna', 'generation' => 'IV', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Toyota', 'name' => 'Lexus RX', 'generation' => 'IV', 'start_year' => 2015, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2019],
            ['brand' => 'Toyota', 'name' => 'Venza', 'generation' => 'II', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Toyota', 'name' => 'Sequoia', 'generation' => 'III', 'start_year' => 2022, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Toyota', 'name' => 'Tacoma', 'generation' => 'III', 'start_year' => 2015, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2020],
            ['brand' => 'Toyota', 'name' => 'Corolla Cross', 'generation' => 'I', 'start_year' => 2021, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Toyota', 'name' => 'Mirai', 'generation' => 'II', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Toyota', 'name' => 'Tundra', 'generation' => 'III', 'start_year' => 2022, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Toyota', 'name' => 'Alphard', 'generation' => 'III', 'start_year' => 2015, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Toyota', 'name' => 'Proace', 'generation' => 'II', 'start_year' => 2021, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Toyota', 'name' => 'Auris', 'generation' => 'II', 'start_year' => 2013, 'end_year' => 2018, 'is_facelift' => true, 'facelift_year' => 2015],
            ['brand' => 'Toyota', 'name' => 'Verso', 'generation' => 'III', 'start_year' => 2013, 'end_year' => 2018, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Toyota', 'name' => 'Crown', 'generation' => 'XV', 'start_year' => 2018, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Toyota', 'name' => 'Civic', 'generation' => 'X', 'start_year' => 2015, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Toyota', 'name' => 'Prius Prime', 'generation' => 'I', 'start_year' => 2016, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Toyota', 'name' => 'Avensis Verso', 'generation' => 'II', 'start_year' => 2009, 'end_year' => 2018, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Toyota', 'name' => 'FJ Cruiser', 'generation' => 'I', 'start_year' => 2006, 'end_year' => 2014, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Toyota', 'name' => 'Urban Cruiser', 'generation' => 'I', 'start_year' => 2009, 'end_year' => 2014, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Toyota', 'name' => 'Yaris Cross', 'generation' => 'I', 'start_year' => 2022, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Toyota', 'name' => 'Hilux SW4', 'generation' => 'II', 'start_year' => 2015, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Toyota', 'name' => 'Fortuner', 'generation' => 'III', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Toyota', 'name' => 'Lexus NX', 'generation' => 'II', 'start_year' => 2021, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Toyota', 'name' => 'Sienta', 'generation' => 'IV', 'start_year' => 2021, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Toyota', 'name' => 'Caldina', 'generation' => 'III', 'start_year' => 2002, 'end_year' => 2007, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Toyota', 'name' => 'Matrix', 'generation' => 'II', 'start_year' => 2009, 'end_year' => 2014, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Toyota', 'name' => 'RAV4 EV', 'generation' => 'I', 'start_year' => 2012, 'end_year' => 2014, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Toyota', 'name' => 'Forte', 'generation' => 'I', 'start_year' => 2013, 'end_year' => 2018, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Toyota', 'name' => 'Camry Hybrid', 'generation' => 'VIII', 'start_year' => 2019, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2022],
            ['brand' => 'Toyota', 'name' => 'Land Cruiser 70', 'generation' => 'I', 'start_year' => 1984, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Toyota', 'name' => 'Voxy', 'generation' => 'III', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Toyota', 'name' => 'C-HR Prologue', 'generation' => 'I', 'start_year' => 2023, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Toyota', 'name' => 'Corolla Sedan', 'generation' => 'XII', 'start_year' => 2019, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Toyota', 'name' => 'Supra', 'generation' => 'V', 'start_year' => 2019, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],

            ['brand' => 'Hyundai', 'name' => 'Elantra', 'generation' => 'VIII', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Hyundai', 'name' => 'Sonata', 'generation' => 'VIII', 'start_year' => 2019, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Hyundai', 'name' => 'Tucson', 'generation' => 'IV', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Hyundai', 'name' => 'Santa Fe', 'generation' => 'IV', 'start_year' => 2018, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Hyundai', 'name' => 'Kona', 'generation' => 'I', 'start_year' => 2017, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2020],
            ['brand' => 'Hyundai', 'name' => 'Palisade', 'generation' => 'I', 'start_year' => 2019, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Hyundai', 'name' => 'Creta', 'generation' => 'II', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Hyundai', 'name' => 'Ioniq', 'generation' => 'I', 'start_year' => 2016, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2019],
            ['brand' => 'Hyundai', 'name' => 'i30', 'generation' => 'III', 'start_year' => 2017, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2020],
            ['brand' => 'Hyundai', 'name' => 'Veloster', 'generation' => 'II', 'start_year' => 2018, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Hyundai', 'name' => 'i10', 'generation' => 'III', 'start_year' => 2019, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Hyundai', 'name' => 'i20', 'generation' => 'III', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Hyundai', 'name' => 'Tucson FCEV', 'generation' => 'IV', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Hyundai', 'name' => 'Nexo', 'generation' => 'I', 'start_year' => 2018, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Hyundai', 'name' => 'Staria', 'generation' => 'I', 'start_year' => 2021, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Hyundai', 'name' => 'Getz', 'generation' => 'III', 'start_year' => 2008, 'end_year' => 2011, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Hyundai', 'name' => 'Matrix', 'generation' => 'II', 'start_year' => 2011, 'end_year' => 2017, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Hyundai', 'name' => 'Elantra GT', 'generation' => 'II', 'start_year' => 2017, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Hyundai', 'name' => 'Sonata Hybrid', 'generation' => 'VIII', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2022],
            ['brand' => 'Hyundai', 'name' => 'Kona Electric', 'generation' => 'I', 'start_year' => 2018, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2021],
            ['brand' => 'Hyundai', 'name' => 'Xcient', 'generation' => 'I', 'start_year' => 2021, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Hyundai', 'name' => 'Santa Fe PHEV', 'generation' => 'IV', 'start_year' => 2021, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Hyundai', 'name' => 'Ioniq 5', 'generation' => 'I', 'start_year' => 2021, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Hyundai', 'name' => 'Tucson Hybrid', 'generation' => 'IV', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Hyundai', 'name' => 'Genesis GV70', 'generation' => 'I', 'start_year' => 2021, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Hyundai', 'name' => 'Kona N', 'generation' => 'I', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Hyundai', 'name' => 'i30 N', 'generation' => 'III', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Hyundai', 'name' => 'Creta PHEV', 'generation' => 'II', 'start_year' => 2022, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Hyundai', 'name' => 'Starex', 'generation' => 'IV', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Hyundai', 'name' => 'Porter', 'generation' => 'II', 'start_year' => 2017, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Hyundai', 'name' => 'Veloster N', 'generation' => 'II', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Hyundai', 'name' => 'SANTA FE 2022', 'generation' => 'IV', 'start_year' => 2022, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2022],
            ['brand' => 'Hyundai', 'name' => 'Ioniq 6', 'generation' => 'I', 'start_year' => 2022, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Hyundai', 'name' => 'Nexo Fuel Cell', 'generation' => 'I', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Hyundai', 'name' => 'Creta Turbo', 'generation' => 'II', 'start_year' => 2022, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Hyundai', 'name' => 'Tucson N', 'generation' => 'IV', 'start_year' => 2022, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Hyundai', 'name' => 'Genesis GV80', 'generation' => 'I', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Hyundai', 'name' => 'Hyundai Bayon', 'generation' => 'I', 'start_year' => 2021, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Hyundai', 'name' => 'Hyundai i20 N', 'generation' => 'III', 'start_year' => 2021, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Hyundai', 'name' => 'Hyundai Staria Lounge', 'generation' => 'I', 'start_year' => 2022, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Hyundai', 'name' => 'Elantra N', 'generation' => 'VIII', 'start_year' => 2021, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Hyundai', 'name' => 'i30 Fastback', 'generation' => 'III', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],

            ['brand' => 'Ford', 'name' => 'Focus', 'generation' => 'IV', 'start_year' => 2018, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2021],
            ['brand' => 'Ford', 'name' => 'Fiesta', 'generation' => 'VII', 'start_year' => 2017, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Ford', 'name' => 'Mondeo', 'generation' => 'V', 'start_year' => 2014, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2019],
            ['brand' => 'Ford', 'name' => 'Kuga', 'generation' => 'III', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Ford', 'name' => 'Edge', 'generation' => 'II', 'start_year' => 2018, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Ford', 'name' => 'Explorer', 'generation' => 'VI', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Ford', 'name' => 'Transit Connect', 'generation' => 'III', 'start_year' => 2018, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Ford', 'name' => 'Ranger', 'generation' => 'IV', 'start_year' => 2022, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Ford', 'name' => 'Puma', 'generation' => 'I', 'start_year' => 2019, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Ford', 'name' => 'Mustang', 'generation' => 'VII', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Ford', 'name' => 'Fiesta ST', 'generation' => 'VII', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Ford', 'name' => 'EcoSport', 'generation' => 'II', 'start_year' => 2017, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2020],
            ['brand' => 'Ford', 'name' => 'Transit Custom', 'generation' => 'II', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Ford', 'name' => 'C-Max', 'generation' => 'III', 'start_year' => 2019, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Ford', 'name' => 'S-Max', 'generation' => 'III', 'start_year' => 2021, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Ford', 'name' => 'Galaxy', 'generation' => 'III', 'start_year' => 2021, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Ford', 'name' => 'Grand C-Max', 'generation' => 'II', 'start_year' => 2021, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Ford', 'name' => 'Tourneo Connect', 'generation' => 'IV', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Ford', 'name' => 'Tourneo Custom', 'generation' => 'III', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Ford', 'name' => 'Ranger Raptor', 'generation' => 'II', 'start_year' => 2022, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Ford', 'name' => 'Kuga Plug-in Hybrid', 'generation' => 'III', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Ford', 'name' => 'Mustang Mach-E', 'generation' => 'I', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Ford', 'name' => 'F-150', 'generation' => 'XIV', 'start_year' => 2021, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Ford', 'name' => 'Edge ST', 'generation' => 'II', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Ford', 'name' => 'Focus ST', 'generation' => 'IV', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Ford', 'name' => 'Fiesta Active', 'generation' => 'VII', 'start_year' => 2018, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2021],
            ['brand' => 'Ford', 'name' => 'Transit', 'generation' => 'VI', 'start_year' => 2019, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2023],
            ['brand' => 'Ford', 'name' => 'EcoSport Titanium', 'generation' => 'II', 'start_year' => 2021, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2022],
            ['brand' => 'Ford', 'name' => 'Kuga Plug-in Hybrid', 'generation' => 'III', 'start_year' => 2021, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Ford', 'name' => 'Focus Active', 'generation' => 'IV', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2023],
            ['brand' => 'Ford', 'name' => 'Mustang GT', 'generation' => 'VII', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2021],
            ['brand' => 'Ford', 'name' => 'F-150 Raptor', 'generation' => 'XIV', 'start_year' => 2021, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Ford', 'name' => 'Ranger Wildtrak', 'generation' => 'IV', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Ford', 'name' => 'F-250 Super Duty', 'generation' => 'XIV', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Ford', 'name' => 'Transit Courier', 'generation' => 'II', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Ford', 'name' => 'F-350 Super Duty', 'generation' => 'XIV', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Ford', 'name' => 'Ranger XLT', 'generation' => 'IV', 'start_year' => 2022, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Ford', 'name' => 'Tourneo Custom Plug-in Hybrid', 'generation' => 'III', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Ford', 'name' => 'Fiesta Titanium', 'generation' => 'VII', 'start_year' => 2021, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2022],
            ['brand' => 'Ford', 'name' => 'Focus Active X', 'generation' => 'IV', 'start_year' => 2021, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2022],
            ['brand' => 'Ford', 'name' => 'S-Max ST-Line', 'generation' => 'III', 'start_year' => 2021, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2022],
            ['brand' => 'Ford', 'name' => 'Galaxy ST-Line', 'generation' => 'III', 'start_year' => 2021, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2022],
            ['brand' => 'Ford', 'name' => 'Focus Vignale', 'generation' => 'IV', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2022],
            ['brand' => 'Ford', 'name' => 'Fiesta Vignale', 'generation' => 'VII', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2022],

            ['brand' => 'Volkswagen', 'name' => 'Golf', 'generation' => 'VIII', 'start_year' => 2019, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Volkswagen', 'name' => 'Polo', 'generation' => 'VI', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Volkswagen', 'name' => 'Passat', 'generation' => 'B8', 'start_year' => 2014, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2019],
            ['brand' => 'Volkswagen', 'name' => 'Tiguan', 'generation' => 'II', 'start_year' => 2016, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2020],
            ['brand' => 'Volkswagen', 'name' => 'Arteon', 'generation' => 'I', 'start_year' => 2017, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2021],
            ['brand' => 'Volkswagen', 'name' => 'Touareg', 'generation' => 'III', 'start_year' => 2018, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Volkswagen', 'name' => 'ID.3', 'generation' => 'I', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Volkswagen', 'name' => 'ID.4', 'generation' => 'I', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Volkswagen', 'name' => 'T-Roc', 'generation' => 'I', 'start_year' => 2017, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2020],
            ['brand' => 'Volkswagen', 'name' => 'Sharan', 'generation' => 'II', 'start_year' => 2010, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Volkswagen', 'name' => 'Caddy', 'generation' => 'V', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Volkswagen', 'name' => 'California', 'generation' => 'VI', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Volkswagen', 'name' => 'Up!', 'generation' => 'II', 'start_year' => 2016, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2019],
            ['brand' => 'Volkswagen', 'name' => 'T-Cross', 'generation' => 'I', 'start_year' => 2019, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Volkswagen', 'name' => 'ID. Buzz', 'generation' => 'I', 'start_year' => 2022, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Volkswagen', 'name' => 'Golf GTI', 'generation' => 'VIII', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Volkswagen', 'name' => 'Golf R', 'generation' => 'VIII', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Volkswagen', 'name' => 'Passat Alltrack', 'generation' => 'B8', 'start_year' => 2015, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2020],
            ['brand' => 'Volkswagen', 'name' => 'Tiguan Allspace', 'generation' => 'II', 'start_year' => 2017, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2021],
            ['brand' => 'Volkswagen', 'name' => 'Touran', 'generation' => 'III', 'start_year' => 2015, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2020],
            ['brand' => 'Volkswagen', 'name' => 'ID.5', 'generation' => 'I', 'start_year' => 2022, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Volkswagen', 'name' => 'Polo GTI', 'generation' => 'VI', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Volkswagen', 'name' => 'Arteon Shooting Brake', 'generation' => 'I', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Volkswagen', 'name' => 'T-Roc Cabriolet', 'generation' => 'I', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Volkswagen', 'name' => 'Passat GTE', 'generation' => 'B8', 'start_year' => 2015, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2020],
            ['brand' => 'Volkswagen', 'name' => 'Caddy California', 'generation' => 'V', 'start_year' => 2021, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Volkswagen', 'name' => 'ID.3 Pro', 'generation' => 'I', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Volkswagen', 'name' => 'Golf Variant', 'generation' => 'VIII', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Volkswagen', 'name' => 'T-Cross Style', 'generation' => 'I', 'start_year' => 2019, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Volkswagen', 'name' => 'ID.4 GTX', 'generation' => 'I', 'start_year' => 2021, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Volkswagen', 'name' => 'Golf eHybrid', 'generation' => 'VIII', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Volkswagen', 'name' => 'ID.3 GTX', 'generation' => 'I', 'start_year' => 2022, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Volkswagen', 'name' => 'T-Roc R', 'generation' => 'I', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Volkswagen', 'name' => 'Polo R-Line', 'generation' => 'VI', 'start_year' => 2021, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Volkswagen', 'name' => 'ID. Buzz Cargo', 'generation' => 'I', 'start_year' => 2022, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Volkswagen', 'name' => 'Golf TGI', 'generation' => 'VIII', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Volkswagen', 'name' => 'Golf Variant R', 'generation' => 'VIII', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Volkswagen', 'name' => 'Tiguan GTE', 'generation' => 'II', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Volkswagen', 'name' => 'Caddy Life', 'generation' => 'V', 'start_year' => 2021, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Volkswagen', 'name' => 'Passat CC', 'generation' => 'B7', 'start_year' => 2008, 'end_year' => 2012, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Volkswagen', 'name' => 'T-Roc Cabriolet R', 'generation' => 'I', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],

            ['brand' => 'Honda', 'name' => 'Civic', 'generation' => 'X', 'start_year' => 2016, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2020],
            ['brand' => 'Honda', 'name' => 'Accord', 'generation' => 'X', 'start_year' => 2017, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2020],
            ['brand' => 'Honda', 'name' => 'CR-V', 'generation' => 'V', 'start_year' => 2016, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2020],
            ['brand' => 'Honda', 'name' => 'HR-V', 'generation' => 'III', 'start_year' => 2021, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Honda', 'name' => 'Jazz', 'generation' => 'IV', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Honda', 'name' => 'Pilot', 'generation' => 'III', 'start_year' => 2016, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2021],
            ['brand' => 'Honda', 'name' => 'Odyssey', 'generation' => 'V', 'start_year' => 2017, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2020],
            ['brand' => 'Honda', 'name' => 'Insight', 'generation' => 'III', 'start_year' => 2018, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Honda', 'name' => 'HR-V', 'generation' => 'II', 'start_year' => 2014, 'end_year' => 2021, 'is_facelift' => true, 'facelift_year' => 2019],
            ['brand' => 'Honda', 'name' => 'Accord Hybrid', 'generation' => 'X', 'start_year' => 2018, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2020],
            ['brand' => 'Honda', 'name' => 'Civic Type R', 'generation' => 'X', 'start_year' => 2017, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2020],
            ['brand' => 'Honda', 'name' => 'Ridgeline', 'generation' => 'II', 'start_year' => 2017, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Honda', 'name' => 'Fit', 'generation' => 'IV', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Honda', 'name' => 'Element', 'generation' => 'I', 'start_year' => 2003, 'end_year' => 2011, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Honda', 'name' => 'City', 'generation' => 'V', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Honda', 'name' => 'CR-V Hybrid', 'generation' => 'V', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Honda', 'name' => 'S660', 'generation' => 'I', 'start_year' => 2015, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2019],
            ['brand' => 'Honda', 'name' => 'Jazz Crosstar', 'generation' => 'IV', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Honda', 'name' => 'Elysion', 'generation' => 'II', 'start_year' => 2013, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Honda', 'name' => 'Acty', 'generation' => 'VII', 'start_year' => 2019, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Honda', 'name' => 'M-NV', 'generation' => 'I', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Honda', 'name' => 'Civic Sedan', 'generation' => 'X', 'start_year' => 2016, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2020],
            ['brand' => 'Honda', 'name' => 'Passport', 'generation' => 'III', 'start_year' => 2019, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Honda', 'name' => 'ZR-V', 'generation' => 'I', 'start_year' => 2022, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Honda', 'name' => 'CBU', 'generation' => 'I', 'start_year' => 2015, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Honda', 'name' => 'Jazz RS', 'generation' => 'IV', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Honda', 'name' => 'Crossroad', 'generation' => 'I', 'start_year' => 2007, 'end_year' => 2012, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Honda', 'name' => 'Clarity', 'generation' => 'I', 'start_year' => 2016, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Honda', 'name' => 'S660 Modulo', 'generation' => 'I', 'start_year' => 2019, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Honda', 'name' => 'Vezel', 'generation' => 'II', 'start_year' => 2021, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Honda', 'name' => 'Stepwgn', 'generation' => 'III', 'start_year' => 2015, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Honda', 'name' => 'Life', 'generation' => 'VI', 'start_year' => 2015, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2019],
            ['brand' => 'Honda', 'name' => 'Acty Truck', 'generation' => 'VII', 'start_year' => 2019, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Honda', 'name' => 'FREED', 'generation' => 'III', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Honda', 'name' => 'Prelude', 'generation' => 'V', 'start_year' => 2002, 'end_year' => 2006, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Honda', 'name' => 'Legend', 'generation' => 'VII', 'start_year' => 2015, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Honda', 'name' => 'Civic Hatchback', 'generation' => 'X', 'start_year' => 2017, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2020],
            ['brand' => 'Honda', 'name' => 'Vezel e:HEV', 'generation' => 'II', 'start_year' => 2022, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Honda', 'name' => 'Odyssey Hybrid', 'generation' => 'V', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Honda', 'name' => 'WR-V', 'generation' => 'II', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Honda', 'name' => 'Civic Si', 'generation' => 'X', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Honda', 'name' => 'CR-V e:HEV', 'generation' => 'V', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Honda', 'name' => 'FREED Spike', 'generation' => 'II', 'start_year' => 2019, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Honda', 'name' => 'S660 Alpha', 'generation' => 'I', 'start_year' => 2019, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Honda', 'name' => 'Acty Van', 'generation' => 'VII', 'start_year' => 2019, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Honda', 'name' => 'Stepwgn Spada', 'generation' => 'III', 'start_year' => 2015, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],

            ['brand' => 'BMW', 'name' => '3 Series', 'generation' => 'G20', 'start_year' => 2018, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2022],
            ['brand' => 'BMW', 'name' => '5 Series', 'generation' => 'G30', 'start_year' => 2016, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2020],
            ['brand' => 'BMW', 'name' => 'X5', 'generation' => 'G05', 'start_year' => 2018, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'BMW', 'name' => 'X3', 'generation' => 'G01', 'start_year' => 2017, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2022],
            ['brand' => 'BMW', 'name' => '7 Series', 'generation' => 'G11', 'start_year' => 2015, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2019],
            ['brand' => 'BMW', 'name' => 'X6', 'generation' => 'G06', 'start_year' => 2019, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'BMW', 'name' => 'Z4', 'generation' => 'G29', 'start_year' => 2018, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'BMW', 'name' => 'M3', 'generation' => 'G80', 'start_year' => 2021, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'BMW', 'name' => 'X1', 'generation' => 'F48', 'start_year' => 2015, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2022],
            ['brand' => 'BMW', 'name' => 'M5', 'generation' => 'F90', 'start_year' => 2017, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2021],
            ['brand' => 'BMW', 'name' => '1 Series', 'generation' => 'F40', 'start_year' => 2019, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'BMW', 'name' => '8 Series', 'generation' => 'G14', 'start_year' => 2018, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'BMW', 'name' => 'M4', 'generation' => 'G82', 'start_year' => 2021, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'BMW', 'name' => 'X7', 'generation' => 'G07', 'start_year' => 2018, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'BMW', 'name' => '4 Series', 'generation' => 'G22', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'BMW', 'name' => 'i3', 'generation' => 'I01', 'start_year' => 2013, 'end_year' => 2022, 'is_facelift' => true, 'facelift_year' => 2017],
            ['brand' => 'BMW', 'name' => 'i8', 'generation' => 'I12', 'start_year' => 2014, 'end_year' => 2020, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'BMW', 'name' => 'X4', 'generation' => 'G02', 'start_year' => 2018, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2022],
            ['brand' => 'BMW', 'name' => 'M2', 'generation' => 'G87', 'start_year' => 2022, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'BMW', 'name' => 'X2', 'generation' => 'F39', 'start_year' => 2018, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2022],
            ['brand' => 'BMW', 'name' => '4 Series Gran Coupe', 'generation' => 'G26', 'start_year' => 2021, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'BMW', 'name' => 'X5 M', 'generation' => 'F85', 'start_year' => 2015, 'end_year' => 2019, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'BMW', 'name' => 'M6', 'generation' => 'F13', 'start_year' => 2012, 'end_year' => 2018, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'BMW', 'name' => 'Z3', 'generation' => 'I', 'start_year' => 1995, 'end_year' => 2002, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'BMW', 'name' => 'X3 M', 'generation' => 'F97', 'start_year' => 2019, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'BMW', 'name' => '3 Series Touring', 'generation' => 'G21', 'start_year' => 2019, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'BMW', 'name' => 'X5 xDrive45e', 'generation' => 'G05', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'BMW', 'name' => 'i4', 'generation' => 'I4', 'start_year' => 2021, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'BMW', 'name' => '2 Series', 'generation' => 'F22', 'start_year' => 2014, 'end_year' => 2021, 'is_facelift' => true, 'facelift_year' => 2017],
            ['brand' => 'BMW', 'name' => 'M5 Competition', 'generation' => 'F90', 'start_year' => 2018, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2021],
            ['brand' => 'BMW', 'name' => '4 Series Convertible', 'generation' => 'G23', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'BMW', 'name' => 'M8', 'generation' => 'G15', 'start_year' => 2019, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'BMW', 'name' => 'X1 M35i', 'generation' => 'F48', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'BMW', 'name' => 'iX', 'generation' => 'I20', 'start_year' => 2022, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'BMW', 'name' => 'M340i', 'generation' => 'G20', 'start_year' => 2019, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2022],
            ['brand' => 'BMW', 'name' => '530e', 'generation' => 'G30', 'start_year' => 2018, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2020],
            ['brand' => 'BMW', 'name' => 'X6 M Competition', 'generation' => 'G06', 'start_year' => 2019, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'BMW', 'name' => 'i3s', 'generation' => 'I01', 'start_year' => 2017, 'end_year' => 2022, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'BMW', 'name' => 'M235i Gran Coupe', 'generation' => 'F44', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'BMW', 'name' => '330e', 'generation' => 'G20', 'start_year' => 2019, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2022],

            ['brand' => 'Mercedes-Benz', 'name' => 'C-Class', 'generation' => 'W205', 'start_year' => 2014, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2018],
            ['brand' => 'Mercedes-Benz', 'name' => 'E-Class', 'generation' => 'W213', 'start_year' => 2016, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2020],
            ['brand' => 'Mercedes-Benz', 'name' => 'S-Class', 'generation' => 'W223', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Mercedes-Benz', 'name' => 'GLE', 'generation' => 'V167', 'start_year' => 2018, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2023],
            ['brand' => 'Mercedes-Benz', 'name' => 'GLC', 'generation' => 'X253', 'start_year' => 2015, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2019],
            ['brand' => 'Mercedes-Benz', 'name' => 'A-Class', 'generation' => 'W177', 'start_year' => 2018, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2022],
            ['brand' => 'Mercedes-Benz', 'name' => 'M-Class', 'generation' => 'W166', 'start_year' => 2011, 'end_year' => 2018, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Mercedes-Benz', 'name' => 'B-Class', 'generation' => 'W246', 'start_year' => 2011, 'end_year' => 2019, 'is_facelift' => true, 'facelift_year' => 2015],
            ['brand' => 'Mercedes-Benz', 'name' => 'CLA', 'generation' => 'C117', 'start_year' => 2013, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2019],
            ['brand' => 'Mercedes-Benz', 'name' => 'GLS', 'generation' => 'X167', 'start_year' => 2019, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Mercedes-Benz', 'name' => 'G-Class', 'generation' => 'W463', 'start_year' => 2018, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2020],
            ['brand' => 'Mercedes-Benz', 'name' => 'E-Class Coupe', 'generation' => 'C238', 'start_year' => 2017, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2020],
            ['brand' => 'Mercedes-Benz', 'name' => 'A-Class Sedan', 'generation' => 'V177', 'start_year' => 2018, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2022],
            ['brand' => 'Mercedes-Benz', 'name' => 'S-Class Coupe', 'generation' => 'C217', 'start_year' => 2014, 'end_year' => 2020, 'is_facelift' => true, 'facelift_year' => 2018],
            ['brand' => 'Mercedes-Benz', 'name' => 'GLA', 'generation' => 'X156', 'start_year' => 2013, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2020],
            ['brand' => 'Mercedes-Benz', 'name' => 'G-Class Cabriolet', 'generation' => 'W463', 'start_year' => 2019, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Mercedes-Benz', 'name' => 'C-Class Cabriolet', 'generation' => 'A205', 'start_year' => 2016, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2020],
            ['brand' => 'Mercedes-Benz', 'name' => 'MAYBACH S-Class', 'generation' => 'W223', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Mercedes-Benz', 'name' => 'AMG GT', 'generation' => 'C190', 'start_year' => 2015, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2020],
            ['brand' => 'Mercedes-Benz', 'name' => 'V-Class', 'generation' => 'W447', 'start_year' => 2014, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2019],
            ['brand' => 'Mercedes-Benz', 'name' => 'EQC', 'generation' => 'N293', 'start_year' => 2019, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Mercedes-Benz', 'name' => 'EQB', 'generation' => 'X243', 'start_year' => 2021, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Mercedes-Benz', 'name' => 'EQV', 'generation' => 'V300', 'start_year' => 2019, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Mercedes-Benz', 'name' => 'C-Class Estate', 'generation' => 'S205', 'start_year' => 2014, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2018],
            ['brand' => 'Mercedes-Benz', 'name' => 'E-Class Estate', 'generation' => 'S213', 'start_year' => 2016, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2020],
            ['brand' => 'Mercedes-Benz', 'name' => 'GLK', 'generation' => 'X204', 'start_year' => 2008, 'end_year' => 2015, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Mercedes-Benz', 'name' => 'G-Class G500', 'generation' => 'W463', 'start_year' => 2019, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Mercedes-Benz', 'name' => 'CLA Shooting Brake', 'generation' => 'X117', 'start_year' => 2015, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2019],
            ['brand' => 'Mercedes-Benz', 'name' => 'GLS Maybach', 'generation' => 'X167', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Mercedes-Benz', 'name' => 'S-Class Sedan', 'generation' => 'W223', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Mercedes-Benz', 'name' => 'SL-Class', 'generation' => 'R232', 'start_year' => 2022, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Mercedes-Benz', 'name' => 'G-Class G63 AMG', 'generation' => 'W463', 'start_year' => 2018, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2020],
            ['brand' => 'Mercedes-Benz', 'name' => 'A-Class L', 'generation' => 'W177', 'start_year' => 2018, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2022],
            ['brand' => 'Mercedes-Benz', 'name' => 'SLC', 'generation' => 'R172', 'start_year' => 2011, 'end_year' => 2020, 'is_facelift' => true, 'facelift_year' => 2016],
            ['brand' => 'Mercedes-Benz', 'name' => 'GLA 45 AMG', 'generation' => 'X156', 'start_year' => 2014, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2020],
            ['brand' => 'Mercedes-Benz', 'name' => 'GLB', 'generation' => 'X247', 'start_year' => 2019, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Mercedes-Benz', 'name' => 'EQE', 'generation' => 'V295', 'start_year' => 2022, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Mercedes-Benz', 'name' => 'EQS', 'generation' => 'V297', 'start_year' => 2021, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Mercedes-Benz', 'name' => 'GLA 35 AMG', 'generation' => 'X156', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],

            ['brand' => 'Chevrolet', 'name' => 'Chevrolet Cruze', 'generation' => 'II', 'start_year' => 2016, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2020],
            ['brand' => 'Chevrolet', 'name' => 'Chevrolet Malibu', 'generation' => 'IX', 'start_year' => 2015, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2019],
            ['brand' => 'Chevrolet', 'name' => 'Chevrolet Tahoe', 'generation' => 'IV', 'start_year' => 2015, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2021],
            ['brand' => 'Chevrolet', 'name' => 'Chevrolet Silverado 1500', 'generation' => 'LD', 'start_year' => 2014, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2019],
            ['brand' => 'Chevrolet', 'name' => 'Chevrolet Traverse', 'generation' => 'II', 'start_year' => 2017, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2021],
            ['brand' => 'Chevrolet', 'name' => 'Chevrolet Spark', 'generation' => 'IV', 'start_year' => 2015, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2019],
            ['brand' => 'Chevrolet', 'name' => 'Chevrolet Equinox', 'generation' => 'II', 'start_year' => 2017, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2021],
            ['brand' => 'Chevrolet', 'name' => 'Chevrolet Camaro', 'generation' => 'VI', 'start_year' => 2015, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2020],
            ['brand' => 'Chevrolet', 'name' => 'Chevrolet Corvette', 'generation' => 'C8', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Chevrolet', 'name' => 'Chevrolet Suburban', 'generation' => 'II', 'start_year' => 2015, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2021],
            ['brand' => 'Chevrolet', 'name' => 'Chevrolet Colorado', 'generation' => 'II', 'start_year' => 2015, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2020],
            ['brand' => 'Chevrolet', 'name' => 'Chevrolet Sonic', 'generation' => 'II', 'start_year' => 2011, 'end_year' => 2020, 'is_facelift' => true, 'facelift_year' => 2016],
            ['brand' => 'Chevrolet', 'name' => 'Chevrolet Captiva', 'generation' => 'I', 'start_year' => 2006, 'end_year' => 2018, 'is_facelift' => true, 'facelift_year' => 2011],
            ['brand' => 'Chevrolet', 'name' => 'Chevrolet Trailblazer', 'generation' => 'II', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Chevrolet', 'name' => 'Chevrolet Bolt EV', 'generation' => 'I', 'start_year' => 2016, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2021],
            ['brand' => 'Chevrolet', 'name' => 'Chevrolet Malibu Hybrid', 'generation' => 'IX', 'start_year' => 2016, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2019],
            ['brand' => 'Chevrolet', 'name' => 'Chevrolet Sonic Sedan', 'generation' => 'II', 'start_year' => 2011, 'end_year' => 2020, 'is_facelift' => true, 'facelift_year' => 2016],
            ['brand' => 'Chevrolet', 'name' => 'Chevrolet Camaro ZL1', 'generation' => 'VI', 'start_year' => 2017, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Chevrolet', 'name' => 'Chevrolet Tahoe Hybrid', 'generation' => 'IV', 'start_year' => 2016, 'end_year' => 2020, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Chevrolet', 'name' => 'Chevrolet Spark EV', 'generation' => 'IV', 'start_year' => 2015, 'end_year' => 2017, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Chevrolet', 'name' => 'Chevrolet Corvette Stingray', 'generation' => 'C7', 'start_year' => 2014, 'end_year' => 2019, 'is_facelift' => true, 'facelift_year' => 2017],
            ['brand' => 'Chevrolet', 'name' => 'Chevrolet Cruze Hatchback', 'generation' => 'II', 'start_year' => 2016, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2020],
            ['brand' => 'Chevrolet', 'name' => 'Chevrolet Sonic Hatchback', 'generation' => 'II', 'start_year' => 2011, 'end_year' => 2020, 'is_facelift' => true, 'facelift_year' => 2016],
            ['brand' => 'Chevrolet', 'name' => 'Chevrolet Malibu Limited', 'generation' => 'VIII', 'start_year' => 2015, 'end_year' => 2016, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Chevrolet', 'name' => 'Chevrolet Silverado HD', 'generation' => 'III', 'start_year' => 2019, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Chevrolet', 'name' => 'Chevrolet Colorado ZR2', 'generation' => 'II', 'start_year' => 2017, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2020],
            ['brand' => 'Chevrolet', 'name' => 'Chevrolet Express', 'generation' => 'G', 'start_year' => 2003, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2020],
            ['brand' => 'Chevrolet', 'name' => 'Chevrolet Suburban RST', 'generation' => 'II', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Chevrolet', 'name' => 'Chevrolet Volt', 'generation' => 'II', 'start_year' => 2016, 'end_year' => 2019, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Chevrolet', 'name' => 'Chevrolet Equinox RS', 'generation' => 'II', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Chevrolet', 'name' => 'Chevrolet Trax', 'generation' => 'II', 'start_year' => 2019, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2023],
            ['brand' => 'Chevrolet', 'name' => 'Chevrolet Silverado Trail Boss', 'generation' => 'LD', 'start_year' => 2017, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2020],
            ['brand' => 'Chevrolet', 'name' => 'Chevrolet Silverado High Country', 'generation' => 'LD', 'start_year' => 2015, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2019],
            ['brand' => 'Chevrolet', 'name' => 'Chevrolet Sonic RS', 'generation' => 'II', 'start_year' => 2016, 'end_year' => 2020, 'is_facelift' => true, 'facelift_year' => 2016],
            ['brand' => 'Chevrolet', 'name' => 'Chevrolet Silverado Custom', 'generation' => 'LD', 'start_year' => 2019, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Chevrolet', 'name' => 'Chevrolet Malibu Premier', 'generation' => 'IX', 'start_year' => 2017, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2019],
            ['brand' => 'Chevrolet', 'name' => 'Chevrolet Tahoe Police Pursuit', 'generation' => 'IV', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2021],
            ['brand' => 'Chevrolet', 'name' => 'Chevrolet Colorado WT', 'generation' => 'II', 'start_year' => 2015, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2020],
            ['brand' => 'Chevrolet', 'name' => 'Chevrolet Silverado Custom Trail Boss', 'generation' => 'LD', 'start_year' => 2019, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],

            ['brand' => 'Audi', 'name' => 'Audi A3', 'generation' => 'IV', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Audi', 'name' => 'Audi A4', 'generation' => 'B9', 'start_year' => 2016, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2020],
            ['brand' => 'Audi', 'name' => 'Audi A6', 'generation' => 'C8', 'start_year' => 2018, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2023],
            ['brand' => 'Audi', 'name' => 'Audi A8', 'generation' => 'D5', 'start_year' => 2017, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2022],
            ['brand' => 'Audi', 'name' => 'Audi Q3', 'generation' => 'II', 'start_year' => 2018, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2023],
            ['brand' => 'Audi', 'name' => 'Audi Q5', 'generation' => 'II', 'start_year' => 2017, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2021],
            ['brand' => 'Audi', 'name' => 'Audi Q7', 'generation' => 'II', 'start_year' => 2015, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2020],
            ['brand' => 'Audi', 'name' => 'Audi Q8', 'generation' => 'I', 'start_year' => 2018, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Audi', 'name' => 'Audi A5', 'generation' => 'F5', 'start_year' => 2017, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2022],
            ['brand' => 'Audi', 'name' => 'Audi A7', 'generation' => 'C8', 'start_year' => 2018, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Audi', 'name' => 'Audi TT', 'generation' => 'III', 'start_year' => 2014, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2018],
            ['brand' => 'Audi', 'name' => 'Audi S3', 'generation' => 'III', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Audi', 'name' => 'Audi S4', 'generation' => 'B9', 'start_year' => 2016, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2020],
            ['brand' => 'Audi', 'name' => 'Audi S5', 'generation' => 'F5', 'start_year' => 2017, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2022],
            ['brand' => 'Audi', 'name' => 'Audi RS3', 'generation' => 'II', 'start_year' => 2017, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2021],
            ['brand' => 'Audi', 'name' => 'Audi RS4', 'generation' => 'B9', 'start_year' => 2017, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2022],
            ['brand' => 'Audi', 'name' => 'Audi RS5', 'generation' => 'F5', 'start_year' => 2017, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2022],
            ['brand' => 'Audi', 'name' => 'Audi RS7', 'generation' => 'C8', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Audi', 'name' => 'Audi RS Q5', 'generation' => 'II', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Audi', 'name' => 'Audi Q2', 'generation' => 'I', 'start_year' => 2016, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2020],
            ['brand' => 'Audi', 'name' => 'Audi e-tron', 'generation' => 'I', 'start_year' => 2018, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2022],
            ['brand' => 'Audi', 'name' => 'Audi e-tron GT', 'generation' => 'I', 'start_year' => 2021, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Audi', 'name' => 'Audi A1', 'generation' => 'II', 'start_year' => 2018, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Audi', 'name' => 'Audi A6 Allroad', 'generation' => 'C8', 'start_year' => 2019, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Audi', 'name' => 'Audi A4 Allroad', 'generation' => 'B9', 'start_year' => 2016, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2020],
            ['brand' => 'Audi', 'name' => 'Audi Q5 Sportback', 'generation' => 'II', 'start_year' => 2021, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Audi', 'name' => 'Audi Q7 e-tron', 'generation' => 'II', 'start_year' => 2017, 'end_year' => 2020, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Audi', 'name' => 'Audi A3 Cabriolet', 'generation' => 'IV', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Audi', 'name' => 'Audi Q3 Sportback', 'generation' => 'II', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Audi', 'name' => 'Audi A6 Avant', 'generation' => 'C8', 'start_year' => 2018, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Audi', 'name' => 'Audi Q5 TFSI e', 'generation' => 'II', 'start_year' => 2021, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Audi', 'name' => 'Audi Q7 TFSI e', 'generation' => 'II', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Audi', 'name' => 'Audi A8 L', 'generation' => 'D5', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Audi', 'name' => 'Audi S3 Sportback', 'generation' => 'III', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Audi', 'name' => 'Audi S4 Avant', 'generation' => 'B9', 'start_year' => 2017, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2020],
            ['brand' => 'Audi', 'name' => 'Audi RS Q8', 'generation' => 'I', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Audi', 'name' => 'Audi SQ5', 'generation' => 'II', 'start_year' => 2017, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2021],
            ['brand' => 'Audi', 'name' => 'Audi RS5 Sportback', 'generation' => 'F5', 'start_year' => 2018, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Audi', 'name' => 'Audi S7', 'generation' => 'C8', 'start_year' => 2019, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Audi', 'name' => 'Audi Q4 e-tron', 'generation' => 'I', 'start_year' => 2021, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Audi', 'name' => 'Audi A1 Citycarver', 'generation' => 'II', 'start_year' => 2019, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Audi', 'name' => 'Audi RS3 Sedan', 'generation' => 'II', 'start_year' => 2021, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],

            ['brand' => 'Kia', 'name' => 'Kia Rio', 'generation' => 'IV', 'start_year' => 2017, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2020],
            ['brand' => 'Kia', 'name' => 'Kia Sportage', 'generation' => 'V', 'start_year' => 2015, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2020],
            ['brand' => 'Kia', 'name' => 'Kia Ceed', 'generation' => 'III', 'start_year' => 2018, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2022],
            ['brand' => 'Kia', 'name' => 'Kia Seltos', 'generation' => 'I', 'start_year' => 2019, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Kia', 'name' => 'Kia Sorento', 'generation' => 'IV', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Kia', 'name' => 'Kia Stinger', 'generation' => 'I', 'start_year' => 2017, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2020],
            ['brand' => 'Kia', 'name' => 'Kia Niro', 'generation' => 'I', 'start_year' => 2016, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2020],
            ['brand' => 'Kia', 'name' => 'Kia Picanto', 'generation' => 'III', 'start_year' => 2017, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2020],
            ['brand' => 'Kia', 'name' => 'Kia Stonic', 'generation' => 'I', 'start_year' => 2017, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Kia', 'name' => 'Kia XCeed', 'generation' => 'I', 'start_year' => 2019, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Kia', 'name' => 'Kia K5', 'generation' => 'VIII', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Kia', 'name' => 'Kia Soul', 'generation' => 'III', 'start_year' => 2019, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2022],
            ['brand' => 'Kia', 'name' => 'Kia Cee’d', 'generation' => 'II', 'start_year' => 2012, 'end_year' => 2018, 'is_facelift' => true, 'facelift_year' => 2015],
            ['brand' => 'Kia', 'name' => 'Kia K7', 'generation' => 'II', 'start_year' => 2019, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Kia', 'name' => 'Kia Carens', 'generation' => 'IV', 'start_year' => 2022, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Kia', 'name' => 'Kia Sorrento PHEV', 'generation' => 'IV', 'start_year' => 2021, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Kia', 'name' => 'Kia Niro EV', 'generation' => 'I', 'start_year' => 2018, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2022],
            ['brand' => 'Kia', 'name' => 'Kia Carnival', 'generation' => 'IV', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Kia', 'name' => 'Kia Soul EV', 'generation' => 'III', 'start_year' => 2019, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Kia', 'name' => 'Kia Optima', 'generation' => 'IV', 'start_year' => 2015, 'end_year' => 2020, 'is_facelift' => true, 'facelift_year' => 2018],
            ['brand' => 'Kia', 'name' => 'Kia Stinger GT', 'generation' => 'I', 'start_year' => 2017, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2020],
            ['brand' => 'Kia', 'name' => 'Kia Forte', 'generation' => 'III', 'start_year' => 2018, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2021],
            ['brand' => 'Kia', 'name' => 'Kia Cadenza', 'generation' => 'II', 'start_year' => 2016, 'end_year' => 2020, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Kia', 'name' => 'Kia Mohave', 'generation' => 'II', 'start_year' => 2019, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Kia', 'name' => 'Kia Optima PHEV', 'generation' => 'IV', 'start_year' => 2017, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Kia', 'name' => 'Kia Niro Plug-In Hybrid', 'generation' => 'I', 'start_year' => 2017, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Kia', 'name' => 'Kia K900', 'generation' => 'II', 'start_year' => 2018, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2021],
            ['brand' => 'Kia', 'name' => 'Kia Soul PHEV', 'generation' => 'III', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Kia', 'name' => 'Kia Seltos PHEV', 'generation' => 'I', 'start_year' => 2021, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Kia', 'name' => 'Kia EV6', 'generation' => 'I', 'start_year' => 2021, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Kia', 'name' => 'Kia Sportage Hybrid', 'generation' => 'V', 'start_year' => 2021, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Kia', 'name' => 'Kia Sorento Hybrid', 'generation' => 'IV', 'start_year' => 2021, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Kia', 'name' => 'Kia Stonic EV', 'generation' => 'I', 'start_year' => 2021, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Kia', 'name' => 'Kia Niro Hybrid', 'generation' => 'I', 'start_year' => 2017, 'end_year' => null, 'is_facelift' => true, 'facelift_year' => 2020],
            ['brand' => 'Kia', 'name' => 'Kia Cee’d GT', 'generation' => 'III', 'start_year' => 2018, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Kia', 'name' => 'Kia Sorrento Plug-in Hybrid', 'generation' => 'IV', 'start_year' => 2021, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Kia', 'name' => 'Kia K8', 'generation' => 'I', 'start_year' => 2021, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Kia', 'name' => 'Kia Carens Hybrid', 'generation' => 'IV', 'start_year' => 2022, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Kia', 'name' => 'Kia Forte GT', 'generation' => 'III', 'start_year' => 2020, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
            ['brand' => 'Kia', 'name' => 'Kia Stinger GT PHEV', 'generation' => 'I', 'start_year' => 2021, 'end_year' => null, 'is_facelift' => false, 'facelift_year' => null],
        ];

        // Создаем записи для каждой модели
        foreach ($popularModels as $modelData) {
            $brand = $brands->firstWhere('name', $modelData['brand']);
            if ($brand) {
                VehicleModel::create([
                    'brand_id' => $brand->id,
                    'name' => $modelData['name'],
                    'generation' => $modelData['generation'],
                    'start_year' => $modelData['start_year'],
                    'end_year' => $modelData['end_year'],
                    'is_facelift' => $modelData['is_facelift'],
                    'facelift_year' => $modelData['is_facelift'] ?? null,
                ]);
            }
        }
    }
}
