@startuml Activity_HandyFix
|Клиент|
start
:Создание заявки на ремонт;
|Менеджер|
:Создание карточки клиента;
:Оформление заказа;
:Назначение исполнителя;
|Механик|
:Просмотр назначенного заказа;
:Выполнение работ;
:Внесение данных о ремонте;
fork
	:Отметка использованных запчастей;
fork again
	:Добавление замечаний;
end fork
:Изменение статуса на "Завершено";
|Менеджер|
:Проверка выполненных работ;
:Выставление счета;
:Информирование клиента;
|Клиент|
:Получение уведомления;
:Оплата работ;
:Оставление отзыва;
stop
@enduml
